<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

// Data mapping: Device Code (= device_name di alarm_raw/devices) => [unit_code, location, series]
$deviceData = [
    'GPE-B-806'   => ['unit_code' => 'GPE7801', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-807'   => ['unit_code' => 'GPE7802', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-808'   => ['unit_code' => 'GPE7803', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-809'   => ['unit_code' => 'GPE7805', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-811'   => ['unit_code' => 'GPE7806', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-812'   => ['unit_code' => 'GPE7807', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-813'   => ['unit_code' => 'GPE7808', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-815'   => ['unit_code' => 'GPE7809', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-816'   => ['unit_code' => 'GPE7810', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-818'   => ['unit_code' => 'GPE7811', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-819'   => ['unit_code' => 'GPE7812', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-820'   => ['unit_code' => 'GPE7813', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-821'   => ['unit_code' => 'GPE7815', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-822'   => ['unit_code' => 'GPE7816', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-825'   => ['unit_code' => 'GPE7817', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-826'   => ['unit_code' => 'GPE7818', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-827'   => ['unit_code' => 'GPE7819', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-828'   => ['unit_code' => 'GPE7820', 'location' => 'SELATAN', 'series' => 'HD 785'],
    'GPE-B-829'   => ['unit_code' => 'GPE7301', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-830'   => ['unit_code' => 'GPE7302', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-831'   => ['unit_code' => 'GPE7303', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-832'   => ['unit_code' => 'GPE7305', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-833'   => ['unit_code' => 'GPE7306', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-835'   => ['unit_code' => 'GPE7307', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-836'   => ['unit_code' => 'GPE7308', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-837'   => ['unit_code' => 'GPE7309', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-838'   => ['unit_code' => 'GPE7310', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-839'   => ['unit_code' => 'GPE7311', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-856'   => ['unit_code' => 'GPE7312', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-857'   => ['unit_code' => 'GPE7313', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    'GPE-B-860'   => ['unit_code' => 'GPE802',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-866'   => ['unit_code' => 'GPE803',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-867'   => ['unit_code' => 'GPE805',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-871'   => ['unit_code' => 'GPE806',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-873'   => ['unit_code' => 'GPE807',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-876'   => ['unit_code' => 'GPE810',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-877'   => ['unit_code' => 'GPE812',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-B-878'   => ['unit_code' => 'GPE813',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-879'   => ['unit_code' => 'GPE815',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-880'   => ['unit_code' => 'GPE816',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-881'   => ['unit_code' => 'GPE817',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-882'   => ['unit_code' => 'GPE819',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-883'   => ['unit_code' => 'GPE820',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-885'   => ['unit_code' => 'GPE821',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-886'   => ['unit_code' => 'GPE822',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-B-887'   => ['unit_code' => 'GPE823',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1000' => ['unit_code' => 'GPE825',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1001' => ['unit_code' => 'GPE826',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1002' => ['unit_code' => 'GPE827',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1003' => ['unit_code' => 'GPE828',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1005' => ['unit_code' => 'GPE829',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1006' => ['unit_code' => 'GPE830',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1007' => ['unit_code' => 'GPE831',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1008' => ['unit_code' => 'GPE832',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1009' => ['unit_code' => 'GPE833',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1010' => ['unit_code' => 'GPE835',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1011' => ['unit_code' => 'GPE836',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1012' => ['unit_code' => 'GPE837',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1013' => ['unit_code' => 'GPE838',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1015' => ['unit_code' => 'GPE839',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1016' => ['unit_code' => 'GPE840',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1017' => ['unit_code' => 'GPE841',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1018' => ['unit_code' => 'GPE842',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1019' => ['unit_code' => 'GPE843',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1020' => ['unit_code' => 'GPE845',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1021' => ['unit_code' => 'GPE701',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1022' => ['unit_code' => 'GPE702',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1023' => ['unit_code' => 'GPE703',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1025' => ['unit_code' => 'GPE705',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1026' => ['unit_code' => 'GPE706',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1027' => ['unit_code' => 'GPE707',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1028' => ['unit_code' => 'GPE708',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1029' => ['unit_code' => 'GPE709',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1030' => ['unit_code' => 'GPE710',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1031' => ['unit_code' => 'GPE711',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1032' => ['unit_code' => 'GPE712',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1033' => ['unit_code' => 'GPE713',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1036' => ['unit_code' => 'GPE715',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1038' => ['unit_code' => 'GPE716',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1039' => ['unit_code' => 'GPE717',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1050' => ['unit_code' => 'GPE718',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1051' => ['unit_code' => 'GPE719',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1052' => ['unit_code' => 'GPE720',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1055' => ['unit_code' => 'GPE721',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1057' => ['unit_code' => 'GPE722',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1059' => ['unit_code' => 'GPE723',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1060' => ['unit_code' => 'GPE725',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1061' => ['unit_code' => 'GPE726',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1062' => ['unit_code' => 'GPE727',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1063' => ['unit_code' => 'GPE728',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1065' => ['unit_code' => 'GPE729',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1066' => ['unit_code' => 'GPE730',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1068' => ['unit_code' => 'GPE731',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1069' => ['unit_code' => 'GPE732',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1070' => ['unit_code' => 'GPE733',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1071' => ['unit_code' => 'GPE735',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1072' => ['unit_code' => 'GPE736',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1073' => ['unit_code' => 'GPE737',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1075' => ['unit_code' => 'GPE738',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1076' => ['unit_code' => 'GPE739',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1077' => ['unit_code' => 'GPE750',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1078' => ['unit_code' => 'GPE751',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1079' => ['unit_code' => 'GPE752',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1080' => ['unit_code' => 'GPE753',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1081' => ['unit_code' => 'GPE755',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1082' => ['unit_code' => 'GPE756',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1083' => ['unit_code' => 'GPE757',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1085' => ['unit_code' => 'GPE758',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1088' => ['unit_code' => 'GPE759',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1089' => ['unit_code' => 'GPE760',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1093' => ['unit_code' => 'GPE761',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1095' => ['unit_code' => 'GPE762',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1096' => ['unit_code' => 'GPE763',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1097' => ['unit_code' => 'GPE765',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1098' => ['unit_code' => 'GPE766',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1100' => ['unit_code' => 'GPE767',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1102' => ['unit_code' => 'GPE768',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1103' => ['unit_code' => 'GPE769',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1105' => ['unit_code' => 'GPE770',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1106' => ['unit_code' => 'GPE771',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1108' => ['unit_code' => 'GPE772',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1109' => ['unit_code' => 'GPE773',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1112' => ['unit_code' => 'GPE775',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1113' => ['unit_code' => 'GPE776',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1125' => ['unit_code' => 'GPE777',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1126' => ['unit_code' => 'GPE778',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1127' => ['unit_code' => 'GPE779',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1128' => ['unit_code' => 'GPE780',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1129' => ['unit_code' => 'GPE781',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1130' => ['unit_code' => 'GPE782',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1131' => ['unit_code' => 'GPE783',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1132' => ['unit_code' => 'GPE785',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1133' => ['unit_code' => 'GPE786',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1135' => ['unit_code' => 'GPE787',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1136' => ['unit_code' => 'GPE788',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1137' => ['unit_code' => 'GPE789',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1138' => ['unit_code' => 'GPE790',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1139' => ['unit_code' => 'GPE791',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1150' => ['unit_code' => 'GPE792',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1151' => ['unit_code' => 'GPE793',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1152' => ['unit_code' => 'GPE795',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1153' => ['unit_code' => 'GPE796',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1155' => ['unit_code' => 'GPE797',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1156' => ['unit_code' => 'GPE798',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1157' => ['unit_code' => 'GPE799',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1158' => ['unit_code' => 'GPE800',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1159' => ['unit_code' => 'GPE850',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1160' => ['unit_code' => 'GPE851',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1161' => ['unit_code' => 'GPE852',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1162' => ['unit_code' => 'GPE853',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1163' => ['unit_code' => 'GPE855',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1165' => ['unit_code' => 'GPE856',  'location' => 'JO SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1166' => ['unit_code' => 'GPE857',  'location' => 'SELATAN', 'series' => 'HD 465'],
    'GPE-DT-1167' => ['unit_code' => 'GPE972',  'location' => 'SELATAN', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1168' => ['unit_code' => 'GPE973',  'location' => 'SELATAN', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1169' => ['unit_code' => 'GPE980',  'location' => 'SELATAN', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1170' => ['unit_code' => 'GPE981',  'location' => 'SELATAN', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1171' => ['unit_code' => 'GPE983',  'location' => 'SELATAN', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1172' => ['unit_code' => 'GPE986',  'location' => 'SELATAN', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1173' => ['unit_code' => 'GPE990',  'location' => 'SELATAN', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1175' => ['unit_code' => 'GPE1023', 'location' => 'SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1176' => ['unit_code' => 'GPE1022', 'location' => 'SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1177' => ['unit_code' => 'GPE1026', 'location' => 'SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1178' => ['unit_code' => 'GPE1027', 'location' => 'SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1179' => ['unit_code' => 'GPE1029', 'location' => 'SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1180' => ['unit_code' => 'GPE1063', 'location' => 'SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1181' => ['unit_code' => 'GPE970',  'location' => 'STB_SITE', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1182' => ['unit_code' => 'GPE971',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1183' => ['unit_code' => 'GPE975',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1185' => ['unit_code' => 'GPE976',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1186' => ['unit_code' => 'GPE978',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1187' => ['unit_code' => 'GPE979',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1188' => ['unit_code' => 'GPE982',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1189' => ['unit_code' => 'GPE987',  'location' => 'STB_SITE', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1190' => ['unit_code' => 'GPE988',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1191' => ['unit_code' => 'GPE989',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1192' => ['unit_code' => 'GPE991',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1193' => ['unit_code' => 'GPE992',  'location' => 'STB_SITE', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1195' => ['unit_code' => 'GPE993',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1196' => ['unit_code' => 'GPE995',  'location' => 'UTARA', 'series' => 'DT LAMA FMX 400'],
    'GPE-DT-1197' => ['unit_code' => 'GPE1011', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1198' => ['unit_code' => 'GPE1012', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1199' => ['unit_code' => 'GPE1013', 'location' => 'STB_SITE', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1200' => ['unit_code' => 'GPE1021', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1201' => ['unit_code' => 'GPE1025', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1202' => ['unit_code' => 'GPE1028', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1203' => ['unit_code' => 'GPE1030', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1205' => ['unit_code' => 'GPE1031', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1206' => ['unit_code' => 'GPE1032', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1207' => ['unit_code' => 'GPE1037', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1208' => ['unit_code' => 'GPE1038', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1209' => ['unit_code' => 'GPE1050', 'location' => 'SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1210' => ['unit_code' => 'GPE1051', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1211' => ['unit_code' => 'GPE1052', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1212' => ['unit_code' => 'GPE1055', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1213' => ['unit_code' => 'GPE1057', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1215' => ['unit_code' => 'GPE1060', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1216' => ['unit_code' => 'GPE1061', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1217' => ['unit_code' => 'GPE1062', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1218' => ['unit_code' => 'GPE1065', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1219' => ['unit_code' => 'GPE1066', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1220' => ['unit_code' => 'GPE1067', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1221' => ['unit_code' => 'GPE1069', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1222' => ['unit_code' => 'GPE1070', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1223' => ['unit_code' => 'GPE1071', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1225' => ['unit_code' => 'GPE1073', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1226' => ['unit_code' => 'GPE1076', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1227' => ['unit_code' => 'GPE1077', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1228' => ['unit_code' => 'GPE1078', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1229' => ['unit_code' => 'GPE1079', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1230' => ['unit_code' => 'GPE1080', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1231' => ['unit_code' => 'GPE1081', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1232' => ['unit_code' => 'GPE1082', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1233' => ['unit_code' => 'GPE1083', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1235' => ['unit_code' => 'GPE1085', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1236' => ['unit_code' => 'GPE1088', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1237' => ['unit_code' => 'GPE1089', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1238' => ['unit_code' => 'GPE1093', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-1239' => ['unit_code' => 'GPE1095', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2630' => ['unit_code' => 'GPE1096', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2631' => ['unit_code' => 'GPE1097', 'location' => 'STB_SITE', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2632' => ['unit_code' => 'GPE1098', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2633' => ['unit_code' => 'GPE1100', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2637' => ['unit_code' => 'GPE1102', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2651' => ['unit_code' => 'GPE1103', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2801' => ['unit_code' => 'GPE1105', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2802' => ['unit_code' => 'GPE1106', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2803' => ['unit_code' => 'GPE1108', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2805' => ['unit_code' => 'GPE1109', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2806' => ['unit_code' => 'GPE1110', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2807' => ['unit_code' => 'GPE1112', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2808' => ['unit_code' => 'GPE1113', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2809' => ['unit_code' => 'GPE1125', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2810' => ['unit_code' => 'GPE1126', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2811' => ['unit_code' => 'GPE1127', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-2812' => ['unit_code' => 'GPE1128', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-917'  => ['unit_code' => 'GPE1129', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-926'  => ['unit_code' => 'GPE1130', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-929'  => ['unit_code' => 'GPE1131', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-932'  => ['unit_code' => 'GPE1132', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-937'  => ['unit_code' => 'GPE1133', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-950'  => ['unit_code' => 'GPE1135', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-951'  => ['unit_code' => 'GPE1136', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-952'  => ['unit_code' => 'GPE1137', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-953'  => ['unit_code' => 'GPE1138', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-955'  => ['unit_code' => 'GPE1139', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-970'  => ['unit_code' => 'GPE1150', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-971'  => ['unit_code' => 'GPE1151', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-973'  => ['unit_code' => 'GPE1152', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-975'  => ['unit_code' => 'GPE1153', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-976'  => ['unit_code' => 'GPE1155', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-977'  => ['unit_code' => 'GPE1156', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-978'  => ['unit_code' => 'GPE1157', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-979'  => ['unit_code' => 'GPE1158', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-980'  => ['unit_code' => 'GPE1159', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-981'  => ['unit_code' => 'GPE1160', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-982'  => ['unit_code' => 'GPE1161', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-985'  => ['unit_code' => 'GPE1162', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-986'  => ['unit_code' => 'GPE1163', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-987'  => ['unit_code' => 'GPE1165', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-988'  => ['unit_code' => 'GPE1166', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-989'  => ['unit_code' => 'GPE1167', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-990'  => ['unit_code' => 'GPE1168', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-991'  => ['unit_code' => 'GPE1169', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-DT-992'  => ['unit_code' => 'GPE1170', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-993'  => ['unit_code' => 'GPE1171', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-995'  => ['unit_code' => 'GPE1172', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-996'  => ['unit_code' => 'GPE1173', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-997'  => ['unit_code' => 'GPE1175', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-998'  => ['unit_code' => 'GPE1176', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-DT-999'  => ['unit_code' => 'GPE1177', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-815'  => ['unit_code' => 'GPE1178', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-860'  => ['unit_code' => 'GPE1179', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-861'  => ['unit_code' => 'GPE1180', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-865'  => ['unit_code' => 'GPE1181', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-866'  => ['unit_code' => 'GPE1182', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-867'  => ['unit_code' => 'GPE1183', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-868'  => ['unit_code' => 'GPE1185', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-869'  => ['unit_code' => 'GPE1186', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-870'  => ['unit_code' => 'GPE1187', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-871'  => ['unit_code' => 'GPE1188', 'location' => 'UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-FT-872'  => ['unit_code' => 'GPE1189', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-FT-873'  => ['unit_code' => 'GPE1190', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-GFTH-875' => ['unit_code' => 'GPE1191', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-701'  => ['unit_code' => 'GPE1192', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-702'  => ['unit_code' => 'GPE1193', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-703'  => ['unit_code' => 'GPE1195', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-705'  => ['unit_code' => 'GPE1196', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-706'  => ['unit_code' => 'GPE1197', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-707'  => ['unit_code' => 'GPE1198', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-708'  => ['unit_code' => 'GPE1199', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-709'  => ['unit_code' => 'GPE1200', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-710'  => ['unit_code' => 'GPE1201', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-711'  => ['unit_code' => 'GPE1202', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-712'  => ['unit_code' => 'GPE1203', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-713'  => ['unit_code' => 'GPE1205', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-715'  => ['unit_code' => 'GPE1206', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-716'  => ['unit_code' => 'GPE1207', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-717'  => ['unit_code' => 'GPE1208', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-718'  => ['unit_code' => 'GPE1209', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-720'  => ['unit_code' => 'GPE1210', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-721'  => ['unit_code' => 'GPE1211', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-722'  => ['unit_code' => 'GPE1212', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-723'  => ['unit_code' => 'GPE1213', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-725'  => ['unit_code' => 'GPE1215', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-726'  => ['unit_code' => 'GPE1216', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-727'  => ['unit_code' => 'GPE1217', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-728'  => ['unit_code' => 'GPE1218', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-729'  => ['unit_code' => 'GPE1219', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-730'  => ['unit_code' => 'GPE1220', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7301' => ['unit_code' => 'GPE1221', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7302' => ['unit_code' => 'GPE1222', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7303' => ['unit_code' => 'GPE1223', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7305' => ['unit_code' => 'GPE1225', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7306' => ['unit_code' => 'GPE1226', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7307' => ['unit_code' => 'GPE1227', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7308' => ['unit_code' => 'GPE1228', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7309' => ['unit_code' => 'GPE1229', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-731'  => ['unit_code' => 'GPE1230', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7310' => ['unit_code' => 'GPE1231', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7311' => ['unit_code' => 'GPE1232', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7312' => ['unit_code' => 'GPE1233', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-7313' => ['unit_code' => 'GPE1235', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-732'  => ['unit_code' => 'GPE1236', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-733'  => ['unit_code' => 'GPE1237', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-735'  => ['unit_code' => 'GPE1238', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-736'  => ['unit_code' => 'GPE1239', 'location' => 'UTARA', 'series' => 'DT BARU FMX 420'],
    'GPE-HD-737'  => ['unit_code' => 'GPE950',  'location' => 'STB_SITE', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-7801' => ['unit_code' => 'GPE977',  'location' => 'STB_SITE', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-7802' => ['unit_code' => 'GPE985',  'location' => 'STB_SITE', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-7803' => ['unit_code' => 'GPE1009', 'location' => 'MUD UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7805' => ['unit_code' => 'GPE1010', 'location' => 'MUD UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7806' => ['unit_code' => 'GPE1015', 'location' => 'STB_SITE', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7807' => ['unit_code' => 'GPE1016', 'location' => 'STB_SITE', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7808' => ['unit_code' => 'GPE1017', 'location' => 'MUD UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7809' => ['unit_code' => 'GPE1018', 'location' => 'MUD UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7810' => ['unit_code' => 'GPE1019', 'location' => 'STB_SITE', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7811' => ['unit_code' => 'GPE1020', 'location' => 'MUD UTARA', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7812' => ['unit_code' => 'GPE996',  'location' => 'JO SELATAN', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-7813' => ['unit_code' => 'GPE997',  'location' => 'JO SELATAN', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-7815' => ['unit_code' => 'GPE1033', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7816' => ['unit_code' => 'GPE1035', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7817' => ['unit_code' => 'GPE1036', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7818' => ['unit_code' => 'GPE1039', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7819' => ['unit_code' => 'GPE1053', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-7820' => ['unit_code' => 'GPE1056', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-798'  => ['unit_code' => 'GPE1058', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-799'  => ['unit_code' => 'GPE1059', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-800'  => ['unit_code' => 'GPE1068', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-802'  => ['unit_code' => 'GPE1072', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-803'  => ['unit_code' => 'GPE1075', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-805'  => ['unit_code' => 'GPE1086', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-806'  => ['unit_code' => 'GPE1087', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-807'  => ['unit_code' => 'GPE1090', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-810'  => ['unit_code' => 'GPE1091', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-813'  => ['unit_code' => 'GPE1092', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-816'  => ['unit_code' => 'GPE1099', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-817'  => ['unit_code' => 'GPE1101', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-819'  => ['unit_code' => 'GPE1107', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-820'  => ['unit_code' => 'GPE1111', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-821'  => ['unit_code' => 'GPE1115', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-822'  => ['unit_code' => 'GPE1116', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-823'  => ['unit_code' => 'GPE1117', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-825'  => ['unit_code' => 'GPE1118', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-826'  => ['unit_code' => 'GPE1119', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-827'  => ['unit_code' => 'GPE1120', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-828'  => ['unit_code' => 'GPE1121', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-829'  => ['unit_code' => 'GPE1122', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-830'  => ['unit_code' => 'GPE1123', 'location' => 'JO SELATAN', 'series' => 'DT BARU FMX 400'],
    'GPE-HD-831'  => ['unit_code' => 'GPE926',  'location' => 'STB_SITE', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-832'  => ['unit_code' => 'GPE929',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-833'  => ['unit_code' => 'GPE931',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-835'  => ['unit_code' => 'GPE917',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-836'  => ['unit_code' => 'DT-03',   'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-837'  => ['unit_code' => 'DT-11',   'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-838'  => ['unit_code' => 'DT-16',   'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-839'  => ['unit_code' => 'DT871',   'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-840'  => ['unit_code' => 'GPE829',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-841'  => ['unit_code' => 'GPE869',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-842'  => ['unit_code' => 'GPE877',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-843'  => ['unit_code' => 'GPE880',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-845'  => ['unit_code' => 'GPE891',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-846'  => ['unit_code' => 'GPE892',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-847'  => ['unit_code' => 'GPE893',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-848'  => ['unit_code' => 'GPE895',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-850'  => ['unit_code' => 'GPE911',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-851'  => ['unit_code' => 'GPE888',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-852'  => ['unit_code' => 'GPE890',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-853'  => ['unit_code' => 'GPE879',  'location' => 'STB_001', 'series' => 'DT LAMA FMX 370'],
    'GPE-HD-855'  => ['unit_code' => 'GPE932',  'location' => 'M.SERVICE', 'series' => 'DT LAMA FMX 400'],
    'GPE-HD-857'  => ['unit_code' => 'GPE937',  'location' => 'M.SERVICE', 'series' => 'DT LAMA FMX 400'],
    'GPE-LV-890'  => ['unit_code' => 'GPE951',  'location' => 'M.SERVICE', 'series' => 'DT LAMA FMX 400'],
    'GPE-LV-891'  => ['unit_code' => 'GPE952',  'location' => 'M.SERVICE', 'series' => 'DT LAMA FMX 400'],
    'GPE-LV-892'  => ['unit_code' => 'GPE953',  'location' => 'M.SERVICE', 'series' => 'DT LAMA FMX 400'],
    'GPE-LV-910'  => ['unit_code' => 'GPE955',  'location' => 'M.SERVICE', 'series' => 'DT LAMA FMX 400'],
    'GPE-WT-836'  => ['unit_code' => 'GPE998',  'location' => 'M.SERVICE', 'series' => 'DT LAMA FMX 400'],
    'GPE-WT-855'  => ['unit_code' => 'GPE999',  'location' => 'M.SERVICE', 'series' => 'DT LAMA FMX 400'],
];

echo "Total mapping data: " . count($deviceData) . " devices\n\n";

// Cek apakah kolom unit_code, location, series sudah ada
$hasUnitCode = Schema::hasColumn('devices', 'unit_code');
$hasLocation = Schema::hasColumn('devices', 'location');
$hasSeries = Schema::hasColumn('devices', 'series');

echo "Kolom unit_code ada: " . ($hasUnitCode ? 'YA' : 'TIDAK') . "\n";
echo "Kolom location ada: " . ($hasLocation ? 'YA' : 'TIDAK') . "\n";
echo "Kolom series ada: " . ($hasSeries ? 'YA' : 'TIDAK') . "\n\n";

// Ambil semua device_id dari alarm_raw (unique)
$rawDevices = DB::table('alarm_raw')
    ->select('device_id', 'device_name')
    ->distinct()
    ->get()
    ->keyBy('device_name'); // key by device_name (= Device Code)

echo "Unique devices di alarm_raw: " . count($rawDevices) . "\n\n";

// Hitung berapa dari 397 device yang ada di alarm_raw
$matched = 0;
$notInRaw = 0;
foreach ($deviceData as $deviceCode => $info) {
    if (isset($rawDevices[$deviceCode])) {
        $matched++;
    } else {
        $notInRaw++;
    }
}
echo "Matched (Device Code ada di alarm_raw): {$matched}\n";
echo "Tidak ditemukan di alarm_raw: {$notInRaw}\n\n";

// Sample yang tidak ditemukan
echo "=== Sample device TIDAK ditemukan di alarm_raw ===\n";
$count = 0;
foreach ($deviceData as $deviceCode => $info) {
    if (!isset($rawDevices[$deviceCode]) && $count < 5) {
        echo "  {$deviceCode}\n";
        $count++;
    }
}
