<?php
// Master Device Data - 397 Units
// Generated from Excel: Device Code | Unit Code | Location | Series

return [
    ['device_name' => 'GPE-B-806', 'unit_code' => 'GPE7801', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-807', 'unit_code' => 'GPE7802', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-808', 'unit_code' => 'GPE7803', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-809', 'unit_code' => 'GPE7805', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-811', 'unit_code' => 'GPE7806', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-812', 'unit_code' => 'GPE7807', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-813', 'unit_code' => 'GPE7808', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-815', 'unit_code' => 'GPE7809', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-816', 'unit_code' => 'GPE7810', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-818', 'unit_code' => 'GPE7811', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-819', 'unit_code' => 'GPE7812', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-820', 'unit_code' => 'GPE7813', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-821', 'unit_code' => 'GPE7815', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-822', 'unit_code' => 'GPE7816', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-825', 'unit_code' => 'GPE7817', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-826', 'unit_code' => 'GPE7818', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-827', 'unit_code' => 'GPE7819', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-828', 'unit_code' => 'GPE7820', 'location' => 'SELATAN', 'series' => 'HD 785'],
    ['device_name' => 'GPE-B-829', 'unit_code' => 'GPE7301', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-830', 'unit_code' => 'GPE7302', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-831', 'unit_code' => 'GPE7303', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-832', 'unit_code' => 'GPE7305', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-833', 'unit_code' => 'GPE7306', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-835', 'unit_code' => 'GPE7307', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-836', 'unit_code' => 'GPE7308', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-837', 'unit_code' => 'GPE7309', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-838', 'unit_code' => 'GPE7310', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-839', 'unit_code' => 'GPE7311', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-856', 'unit_code' => 'GPE7312', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-857', 'unit_code' => 'GPE7313', 'location' => 'SELATAN', 'series' => 'OHT 773'],
    ['device_name' => 'GPE-B-860', 'unit_code' => 'GPE802', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-866', 'unit_code' => 'GPE803', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-867', 'unit_code' => 'GPE805', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-871', 'unit_code' => 'GPE806', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-873', 'unit_code' => 'GPE807', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-876', 'unit_code' => 'GPE810', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-877', 'unit_code' => 'GPE812', 'location' => 'JO SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-878', 'unit_code' => 'GPE813', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-879', 'unit_code' => 'GPE815', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-880', 'unit_code' => 'GPE816', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-881', 'unit_code' => 'GPE817', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-882', 'unit_code' => 'GPE819', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-883', 'unit_code' => 'GPE820', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-885', 'unit_code' => 'GPE821', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-886', 'unit_code' => 'GPE822', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-B-887', 'unit_code' => 'GPE823', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-DT-1000', 'unit_code' => 'GPE825', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-DT-1001', 'unit_code' => 'GPE826', 'location' => 'SELATAN', 'series' => 'HD 465'],
    ['device_name' => 'GPE-DT-1002', 'unit_code' => 'GPE827', 'location' => 'SELATAN', 'series' => 'HD 465'],
